rosbot:
  # Settings for ros_control hardware interface
  hardware_interface:
     joints:
        - left_wheel_joint
        - right_wheel_joint

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: 'joint_state_controller/JointStateController'
    publish_rate: 50


  mobile_base_controller:
    type: 'diff_drive_controller/DiffDriveController'
    publish_rate: 50

    left_wheel: 'left_wheel_joint'
    right_wheel: 'right_wheel_joint'

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.11
    wheel_radius : 0.025

    # Odometry covariances for the encoder output of the robot. These values should
    # be tuned to your robot's sample odometry data, but these values are a good place
    # to start
    # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.0001]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.0001]

    # Top level frame (link) of the robot description
    base_frame_id: base_link
    # disable publishing odom because ORB SLAM don't use it
    enable_odom_tf: false

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.0375  # m/s
        has_acceleration_limits: false
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.34   # rad/s
        has_acceleration_limits: false
