TrajectoryPlannerROS:
  # Dynamic Window Approach or Trajectory Rollout
  dwa: false

  # these parameters should be much greater than actual robot characteristics,
  # in the case when they are too small robot will be rotating infinetely
  max_vel_x: 0.5
  min_vel_x: 0.1

  max_vel_theta: 0.15 # make this velocity lower than it can be to stabilize ORB SLAM localizaton
  min_vel_theta: -0.15
  min_in_place_vel_theta: 0.1

  # Differential robot
  holonomic_robot: false

  # Are distance parameters expressed in units of meters or cells. Cells are assumed by default.
  meter_scoring: true

  # The weighting for how much the controller should stay close to the path it was given
  pdist_scale: 1.5
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  gdist_scale: 1.0
  # The weighting for how much the controller should attempt to avoid obstacles
  occdist_scale: 0.01

  # Speed used for driving during escapes in meters/sec. Note that it must be negative in order for the robot to actually reverse.
  # 0.0 prevents robot to move backward along the trajectory
  escape_vel: -0.01

