plugins:
  - {name: static_map,       type: "costmap_2d::StaticLayer"}
  - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
  - {name: infaltion,        type: "costmap_2d::InflationLayer"}

# robot parameters
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.01

# dynamic sensor parameters
obstacle_range: 0.5
raytrace_range: 1.5

observation_sources: point_cloud_sensor
point_cloud_sensor: {sensor_frame: top_camera, data_type: PointCloud2, topic: /octomap_point_cloud_centers, marking: true, clearing: true}

# static map parameters
inflation_radius: 0.08
cost_scaling_factor: 85.0
static_map: false
