<?xml version="1.0"?>
<robot name="rosbot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_mass" value="0.9" />
  <xacro:property name="base_length" value="0.145" />
  <xacro:property name="base_width"  value="0.1" />
  <xacro:property name="base_height" value="0.11" />

  <xacro:property name="wheel_mass" value="0.01" />
  <xacro:property name="wheel_radius" value="0.025" />
  <xacro:property name="wheel_width" value="0.005" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" />
   </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(x*x+z*z)/12}" iyz = "0"
                  izz="${m*(x*x+z*z)/12}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
         <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
  </link>

  <xacro:include filename="$(find bot_description)/urdf/camera.urdf.xacro" />
  <xacro:include filename="$(find bot_description)/urdf/wheel.urdf.xacro" />

  <xacro:wheel prefix="right" reflect="1"/>
  <xacro:wheel prefix="left" reflect="-1"/>

  <link name="rear_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${wheel_mass}" r="${wheel_mass}"/>
  </link>

  <joint name="rear_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${-base_length/3.6} 0 -${base_height/2}"/>
  </joint>

  <gazebo reference="rear_wheel">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/rosbot</robotNamespace>
    </plugin>
  </gazebo>
</robot>
